name: Deploy to NPM CDN
'on':
  - workflow_dispatch
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker pull notfl3/cargo-apk
      - run: docker run --rm -v $(pwd):/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --release
      - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android  # 设置Artifact的名称
        path: ./target/release/macroquad_learn.apk   # 设置Artifact的路径