name: Build

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull not-fl3/cargo-apk
      - run: docker run --rm -v $(pwd):/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --release
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target